# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastSigLm <- function(y, X) {
    .Call('_FusioMR_fastSigLm', PACKAGE = 'FusioMR', y, X)
}

gibbs_memo_joint <- function(niter, Gamma_hat_1, Gamma_hat_2, gamma_hat_1, gamma_hat_2, s_hat_Gamma_1, s_hat_Gamma_2, s_hat_gamma_1, s_hat_gamma_2) {
    .Call('_FusioMR_gibbs_memo_joint', PACKAGE = 'FusioMR', niter, Gamma_hat_1, Gamma_hat_2, gamma_hat_1, gamma_hat_2, s_hat_Gamma_1, s_hat_Gamma_2, s_hat_gamma_1, s_hat_gamma_2)
}

gibbs_semo_nohp <- function(niter, Gamma_hat_1, Gamma_hat_2, gamma_hat, s_hat_Gamma_1, s_hat_Gamma_2, s_hat_gamma) {
    .Call('_FusioMR_gibbs_semo_nohp', PACKAGE = 'FusioMR', niter, Gamma_hat_1, Gamma_hat_2, gamma_hat, s_hat_Gamma_1, s_hat_Gamma_2, s_hat_gamma)
}

gibbs_seso_nohp <- function(niter, Gamma_hat, gamma_hat, s2_hat_Gamma, s2_hat_gamma) {
    .Call('_FusioMR_gibbs_seso_nohp', PACKAGE = 'FusioMR', niter, Gamma_hat, gamma_hat, s2_hat_Gamma, s2_hat_gamma)
}

gibbs_seso_uhp_only <- function(niter, Gamma_hat, gamma_hat, s2_hat_Gamma, s2_hat_gamma) {
    .Call('_FusioMR_gibbs_seso_uhp_only', PACKAGE = 'FusioMR', niter, Gamma_hat, gamma_hat, s2_hat_Gamma, s2_hat_gamma)
}

my_rinvwishart <- function(nu, S) {
    .Call('_FusioMR_my_rinvwishart', PACKAGE = 'FusioMR', nu, S)
}

my_rdirichlet <- function(n, alpha) {
    .Call('_FusioMR_my_rdirichlet', PACKAGE = 'FusioMR', n, alpha)
}

