# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastSigLm <- function(y, X) {
    .Call(`_FusioMR_fastSigLm`, y, X)
}

my_rinvwishart <- function(nu, S) {
    .Call(`_FusioMR_my_rinvwishart`, nu, S)
}

gibbs_semo_nohp <- function(niter, Gamma_hat_1, Gamma_hat_2, gamma_hat, s2_hat_Gamma_1, s2_hat_Gamma_2, s2_hat_gamma) {
    .Call(`_FusioMR_gibbs_semo_nohp`, niter, Gamma_hat_1, Gamma_hat_2, gamma_hat, s2_hat_Gamma_1, s2_hat_Gamma_2, s2_hat_gamma)
}

gibbs_seso_nohp <- function(niter, Gamma_hat, gamma_hat, s2_hat_Gamma, s2_hat_gamma) {
    .Call(`_FusioMR_gibbs_seso_nohp`, niter, Gamma_hat, gamma_hat, s2_hat_Gamma, s2_hat_gamma)
}

gibbs_seso_uhp_only <- function(niter, Gamma_hat, gamma_hat, s2_hat_Gamma, s2_hat_gamma) {
    .Call(`_FusioMR_gibbs_seso_uhp_only`, niter, Gamma_hat, gamma_hat, s2_hat_Gamma, s2_hat_gamma)
}

